services:
  ollama:
    image: ollama/ollama:latest
    container_name: gzh_ollama
    ports:
      - "07011:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data:
